# Site settings
title: "Wind"
theme_color: "#5E5E81"
description: "Wind" 
baseurl: ""
url: ""  

relative_permalinks: false
permalink: /:title/
 
 

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-menus

include: ["_pages"]

exclude:
  - node_modules
  - gulpfile.js
  - package.json 
  - package-lock.json
  - yarn.lock
  - sass-cache
  - jekyll-cache
  - jekyll-metadata
  - .vscode   
  - Gemfile 
  - .forestry
  - _config_development.yml
  - _config_staging.yml
