title: "Wind"
theme_color: "#5E5E81"
description: "Wind" 
baseurl: ""
url: "" 

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

relative_permalinks: false
permalink: /:title/
 
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-menus

include: ["_pages"]


 